export const generateReportHTML = ({ username, date, bmi }) => {
    return `
  <!DOCTYPE html>
  <html>
  <head>
    <meta charset="UTF-8" />
    <title>Health Report</title>
    <style>
      body {
        font-family: Arial, sans-serif;
        background: #f4f6f8;
        padding: 20px;
      }
      .container {
        background: white;
        padding: 20px;
        border-radius: 10px;
      }
      .header {
        text-align: center;
        border-bottom: 2px solid #0a84ff;
        padding-bottom: 10px;
      }
      .title {
        color: #0a84ff;
        font-size: 24px;
        font-weight: bold;
      }
      .section {
        margin-top: 20px;
      }
      .label {
        font-weight: bold;
      }
      .warning {
        color: #ff3b30;
        font-weight: bold;
      }
      .footer {
        margin-top: 30px;
        font-size: 12px;
        color: gray;
        border-top: 1px solid #ccc;
        padding-top: 10px;
      }
    </style>
  </head>
  
  <body>
    <div class="container">
      <div class="header">
        <div class="title">SmartWatchApp – Health Report</div>
        <div>${date}</div>
      </div>
  
      <div class="section">
        <div><span class="label">User:</span> ${username}</div>
        <div><span class="label">BMI:</span> ${bmi}</div>
      </div>
  
      <div class="section">
        <div class="warning">
          This is a dummy report generated for testing.
        </div>
      </div>
  
      <div class="footer">
        Disclaimer: This report is generated by SmartWatchApp and should not
        be used as a medical diagnosis. Consult a physician if needed.
      </div>
    </div>
  </body>
  </html>
  `;
  };
  